version: '3.7'

services:

  php:
    build:
      context: .
      dockerfile: resources/dc/php/Dockerfile
    entrypoint: []
    command: []
    tty: true
    stdin_open: true
    volumes:
      - '.:/app'
    depends_on:
      - database
    networks:
      - default

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: groot
    volumes:
      - './resources/dc/mysql/employees.sql:/docker-entrypoint-initdb.d/employees.sql:ro'
      - './resources/dc/mysql/mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/mysqlsampledatabase.sql:ro'
      - './resources/dc/mysql/sakila-mv-schema.sql:/docker-entrypoint-initdb.d/sakila-mv-schema.sql:ro'
    networks:
      - default

networks:
  default:
